imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @IntranetBundle/Resources/config/defined.php }
    - { resource: @IntranetBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%language%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true



# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
               - 'IntranetBundle:Form:_campaign_adsizeHeight_row.html.twig'


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ IntranetBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                

# Swiftmailer Configuration
swiftmailer:
    transport:   "%mailer_transport%"
    host:        "%mailer_host%"
    username:    "%mailer_user%"
    password:    "%mailer_password%"
    spool:
        type: file
        path: "%kernel.root_dir%/spool"


parameters:
    kernel.listener.atd.access_denied.class: Beon\IntranetBundle\Listener\AccessDeniedListener

services:
#    form_helper:
#    class:   Beon\IntranetBundle\Helper\FormHelper
      beon.twig.beon_extension:
              class: Beon\IntranetBundle\Twig\BeonExtension
              tags:
                  - { name: twig.extension }
#      kernel.listener.accessDenied:
#              class: %kernel.listener.atd.access_denied.class%
#              scope: request
#              arguments: ["@session", "@router", "@request"]
#              tags:
#                 - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }

      beon.css_rewrite_filter:
              class: Beon\IntranetBundle\Assetic\Filter\BeonCssRewriterFilter
              tags:
                 - { name: assetic.filter, alias: beon_css_rewriter_filter }

      twig.extension.text:
          class: Twig_Extensions_Extension_Text
          tags:
              - { name: twig.extension }

      demo.tokens.action_listener:
          class: Beon\IntranetBundle\EventListener\TokenListener
          tags:
              - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }


twig:
    form:
        resources:
            - 'IntranetBundle:Form:fields.html.twig'
    globals:
        defaultDateFormat: d.m.Y
        defaultDateTimeFormat: d.m.Y H:i:s




deploy:
  staging:
    rsync-options: '--chmod=ug=rwx -azC --force --delete --progress -h --checksum'
    host: s503663270.online.de
    dir: intranet-staging/
    user: u75435922
    port: 22
    timeout: 200 # Connection timeout in seconds. 0 for no timeout.
    post_deploy_operations:
        - app/console doctrine:migrations:migrate
        - app/console doctrine:schema:update --force
        - app/console cache:clear --env=dev
        - app/console cache:clear --env=prod
        - app/console assets:install ../web
        - app/console assetic:dump

  production:
    rsync-options: '--chmod=ug=rwx -azC --force --delete --progress -h --checksum'
    host: s503663270.online.de
    dir: intranet-production/
    user: u75435922
    port: 22
    timeout: 140 # Connection timeout in seconds. 0 for no timeout.
    post_deploy_operations:
        - app/console doctrine:migrations:migrate
        - app/console doctrine:schema:update --dump-sql
        - app/console cache:clear --env=prod
        - app/console assets:install ../web
        - app/console assetic:dump
