<?php

namespace Proxies\__CG__\Beon\IntranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SupplierGroup extends \Beon\IntranetBundle\Entity\SupplierGroup implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'id', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'name', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'suppliers', 'contacts', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'frameworkContract', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'discount', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'notes', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'bonusInKind', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'uploads');
        }

        return array('__isInitialized__', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'id', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'name', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'suppliers', 'contacts', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'frameworkContract', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'discount', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'notes', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'bonusInKind', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SupplierGroup' . "\0" . 'uploads');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SupplierGroup $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addSupplier(\Beon\IntranetBundle\Entity\Supplier $suppliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSupplier', array($suppliers));

        return parent::addSupplier($suppliers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSupplier(\Beon\IntranetBundle\Entity\Supplier $suppliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSupplier', array($suppliers));

        return parent::removeSupplier($suppliers);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppliers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppliers', array());

        return parent::getSuppliers();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addUpload(\Beon\IntranetBundle\Entity\Upload $uploads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUpload', array($uploads));

        return parent::addUpload($uploads);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload(\Beon\IntranetBundle\Entity\Upload $uploads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array($uploads));

        return parent::removeUpload($uploads);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploads', array());

        return parent::getUploads();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\Beon\IntranetBundle\Entity\Contact $contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', array($contacts));

        return parent::addContact($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\Beon\IntranetBundle\Entity\Contact $contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', array($contacts));

        return parent::removeContact($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', array());

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getFrameworkContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrameworkContract', array());

        return parent::getFrameworkContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrameworkContract($frameworkContract)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrameworkContract', array($frameworkContract));

        return parent::setFrameworkContract($frameworkContract);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', array());

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', array($discount));

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonusInKind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonusInKind', array());

        return parent::getBonusInKind();
    }

    /**
     * {@inheritDoc}
     */
    public function setBonusInKind($bonusInKind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonusInKind', array($bonusInKind));

        return parent::setBonusInKind($bonusInKind);
    }

}
