<?php

namespace Proxies\__CG__\Beon\IntranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SurveyResult extends \Beon\IntranetBundle\Entity\SurveyResult implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'id', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'date', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'timeIn', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'timeOut', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'frequency', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'welcome', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinks', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinksValue', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinksWait', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'food', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'foodValue', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'foodWait', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'service', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'music', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'atmosphere', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'happyHour', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'enchiladaHour', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'casinoMexicano', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'ladiesNight', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'overall', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'customer');
        }

        return array('__isInitialized__', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'id', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'date', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'timeIn', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'timeOut', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'frequency', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'welcome', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinks', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinksValue', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'drinksWait', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'food', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'foodValue', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'foodWait', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'service', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'music', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'atmosphere', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'happyHour', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'enchiladaHour', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'casinoMexicano', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'ladiesNight', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'overall', '' . "\0" . 'Beon\\IntranetBundle\\Entity\\SurveyResult' . "\0" . 'customer');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SurveyResult $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel($field)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array($field));

        return parent::getLabel($field);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeIn($timeIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeIn', array($timeIn));

        return parent::setTimeIn($timeIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeIn', array());

        return parent::getTimeIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeOut($timeOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeOut', array($timeOut));

        return parent::setTimeOut($timeOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeOut', array());

        return parent::getTimeOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequency($frequency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequency', array($frequency));

        return parent::setFrequency($frequency);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequency', array());

        return parent::getFrequency();
    }

    /**
     * {@inheritDoc}
     */
    public function setWelcome($welcome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWelcome', array($welcome));

        return parent::setWelcome($welcome);
    }

    /**
     * {@inheritDoc}
     */
    public function getWelcome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWelcome', array());

        return parent::getWelcome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrinks($drinks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrinks', array($drinks));

        return parent::setDrinks($drinks);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrinks', array());

        return parent::getDrinks();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrinksValue($drinksValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrinksValue', array($drinksValue));

        return parent::setDrinksValue($drinksValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrinksValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrinksValue', array());

        return parent::getDrinksValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrinksWait($drinksWait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrinksWait', array($drinksWait));

        return parent::setDrinksWait($drinksWait);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrinksWait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrinksWait', array());

        return parent::getDrinksWait();
    }

    /**
     * {@inheritDoc}
     */
    public function setFood($food)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFood', array($food));

        return parent::setFood($food);
    }

    /**
     * {@inheritDoc}
     */
    public function getFood()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFood', array());

        return parent::getFood();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoodValue($foodValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoodValue', array($foodValue));

        return parent::setFoodValue($foodValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoodValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoodValue', array());

        return parent::getFoodValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoodWait($foodWait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoodWait', array($foodWait));

        return parent::setFoodWait($foodWait);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoodWait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoodWait', array());

        return parent::getFoodWait();
    }

    /**
     * {@inheritDoc}
     */
    public function setService($service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', array($service));

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', array());

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setMusic($music)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMusic', array($music));

        return parent::setMusic($music);
    }

    /**
     * {@inheritDoc}
     */
    public function getMusic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMusic', array());

        return parent::getMusic();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtmosphere($atmosphere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtmosphere', array($atmosphere));

        return parent::setAtmosphere($atmosphere);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtmosphere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtmosphere', array());

        return parent::getAtmosphere();
    }

    /**
     * {@inheritDoc}
     */
    public function setHappyHour($happyHour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHappyHour', array($happyHour));

        return parent::setHappyHour($happyHour);
    }

    /**
     * {@inheritDoc}
     */
    public function getHappyHour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHappyHour', array());

        return parent::getHappyHour();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnchiladaHour($enchiladaHour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnchiladaHour', array($enchiladaHour));

        return parent::setEnchiladaHour($enchiladaHour);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnchiladaHour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnchiladaHour', array());

        return parent::getEnchiladaHour();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasinoMexicano($casinoMexicano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasinoMexicano', array($casinoMexicano));

        return parent::setCasinoMexicano($casinoMexicano);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasinoMexicano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasinoMexicano', array());

        return parent::getCasinoMexicano();
    }

    /**
     * {@inheritDoc}
     */
    public function setLadiesNight($ladiesNight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLadiesNight', array($ladiesNight));

        return parent::setLadiesNight($ladiesNight);
    }

    /**
     * {@inheritDoc}
     */
    public function getLadiesNight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLadiesNight', array());

        return parent::getLadiesNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverall($overall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverall', array($overall));

        return parent::setOverall($overall);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverall', array());

        return parent::getOverall();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\Beon\IntranetBundle\Entity\Customer $customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

}
