<?php

namespace Beon\IntranetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnumRepository extends FilteredRepository
{
    public function getAllValues($className) {
        return $this->createQueryBuilder('ev')
            ->andWhere('ev.className = :className')
            ->setParameter('className', $className)
            ->getQuery()
            ->getResult();
    }

    public function getResuableValues($className) {
        return $this->getResuableValuesQb($className)
            ->getQuery()
            ->getResult();
    }

    public function getResuableValuesQb($className) {
        return $this->createQueryBuilder('ev')
            ->andWhere('ev.className = :className')
            ->setParameter('className', $className)
            ->andWhere('ev.reusable = true');
    }

    public function findValue($className, $valueStr) {
        return $this->createQueryBuilder('ev')
            ->andWhere('ev.className = :className')
            ->setParameter('className', $className)
            ->andWhere('ev.value = :valueStr')
            ->setParameter('valueStr', $valueStr)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
