<?php

namespace Beon\IntranetBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * mailqueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends EntityRepository
{
	public function findCronData($cronType, $sentDate)
	{
	    $result = $this->getEntityManager()->createQueryBuilder()
	    ->select('MailQueue')
	    ->from('IntranetBundle:MailQueue', 'MailQueue')
	    ->where('MailQueue.sentDate <:sentDate')
	    ->andwhere(('MailQueue.lastApprovalReminderSentAt <:sentDate'))
	    ->setParameter('sentDate', $sentDate);
	    
	    if ($cronType=='task') {
		$result->andwhere("MailQueue.entity LIKE '%Task%'");
	    } else if ($cronType=='campaign') {
		$result->andwhere("MailQueue.entity LIKE '%Campaign%'");
	    } else if ($cronType=='pressRelease') {
		$result->andwhere("MailQueue.entity LIKE '%Pressrelease%'");
	    }
	    
	    return $result->getQuery()->execute();
	}
}