parameters:
    translator.class: Beon\IntranetBundle\Lib\FallbackTranslator
    bollean.type.guesser.class: Beon\IntranetBundle\Guesser\BooleanTypeGuesser
    bollean.type.form.class: Beon\IntranetBundle\Form\Type\BoolchoiceType
    multiple.file.type.form.class: Beon\IntranetBundle\Form\Type\MultipleFileType
services:
    beon.translator:
        class: %translator.class%
        calls:
            - [setRequest, ["@?request="]]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    login_successful_listener:
       class: Beon\IntranetBundle\EventListener\LoginListener
       arguments: [@doctrine]
       tags:
           - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    login_unsuccessful_listener:
        class: Beon\IntranetBundle\EventListener\LoginListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onLoginFailor }
            
    beon.booleanguesser:
        class:  %bollean.type.guesser.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type_guesser }
            
    beon.boolean.type.boolchoice:
        class: %bollean.type.form.class%
        tags:
            - { name: form.type, alias: boolchoice }
         
    beon.file.type.multiplefile:
        class: %multiple.file.type.form.class%
        tags:
            - { name: form.type, alias: multiplefile }
            
    UploadFileService:
        class:        Beon\IntranetBundle\Service\UploadFileService
        arguments: [@service_container,@templating, @mailer, @router]
        
    ReminderMailService:
        class:        Beon\IntranetBundle\Service\ReminderMailService
        arguments: [  @service_container, @templating, @mailer ]
        
    UserCustomerFilterService:
        class: Beon\IntranetBundle\Controller\UserCustomerFilterController