Beon\IntranetBundle\Entity\ConfigValue:
    repositoryClass: Beon\IntranetBundle\Entity\Repository\ConfigRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: string
        description:
            type: string
            length: 255
        role:
            type: string
            length: 255
    lifecycleCallbacks: {  }
