city:
    path:     /
    defaults: { _controller: "IntranetBundle:City:index" }

city_show:
    path:     /{id}/show
    defaults: { _controller: "IntranetBundle:City:show" }

city_new:
    path:     /new
    defaults: { _controller: "IntranetBundle:City:new" }

city_create:
    path:     /create
    defaults: { _controller: "IntranetBundle:City:create" }
    requirements: { _method: post }

city_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntranetBundle:City:edit" }

city_update:
    path:     /{id}/update
    defaults: { _controller: "IntranetBundle:City:update" }
    requirements: { _method: post|put }

city_delete:
    path:     /{id}/delete
    defaults: { _controller: "IntranetBundle:City:delete" }
    requirements: { _method: post|delete }

city_contact:
    pattern: /contact-city
    defaults: { _controller: "IntranetBundle:City:contactCityRelation" }
    requirements: { _method: post }

city_contact_delete:
    pattern: /{id}/{contactId}/contact-city-delete
    defaults: { _controller: "IntranetBundle:City:contactCityDelete" }
    requirements: { _method: get|delete }
